CREATE TABLE employee (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    country_code VARCHAR(10) NOT NULL DEFAULT '+91',
    phone VARCHAR(20) NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR(50) NOT NULL,
    state VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    company_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,
    joined DATE NOT NULL,
    employment_type VARCHAR(50) NOT NULL,
    wages DECIMAL(15, 2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    aadhaar VARCHAR(12) NOT NULL,
    pan VARCHAR(10) NOT NULL,
    esic VARCHAR(50),
    insurance VARCHAR(50),
    account_number VARCHAR(50) NOT NULL,
    ifsc VARCHAR(11) NOT NULL,
    bank_name VARCHAR(255),
    aadhaar_proof VARCHAR(255),
    pan_proof VARCHAR(255),
    insurance_proof VARCHAR(255),
    CONSTRAINT fk_employee_company FOREIGN KEY(company_id) REFERENCES company(id) ON DELETE RESTRICT,
    CONSTRAINT fk_employee_department FOREIGN KEY(department_id) REFERENCES department(id) ON DELETE RESTRICT
);
